import login from './login'
import home from './home'
import user from './user'
import order from './order'
import city from './city'
import carTypes from './carTypes'
import consume from './consume'
import sit from './sit'
import location from './location'
import product from './product'
import address from './address'
import search from './search'
import evaluate from './evaluate'
import coupon from './coupon'
import discovery from './discovery'

export default [discovery, coupon, evaluate, search, home, login, user, order, city, carTypes, consume, sit, location, product, address]
